language: go
go:
- 1.10.4
addons:
  apt:
    packages:
    - time
sudo: false
notifications:
  email:
    on_success: never
    on_failure: always
env: PROJECT_NAME=cronner GOARCH=amd64 GOOS=linux PROJECT_BUILD_NAME="$PROJECT_NAME-$GOOS-$GOARCH-$TRAVIS_TAG"
install: true
before_script:
- rm -rf  ${GOPATH}/pkg/*
script: make test
before_deploy:
- make prep-deploy
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: sGH346h2W9xXsMY4LT5XOUNUukeQ7JwqMaMyDjC5mVkwkVGDczx/TLzzcPFKL51kYIjbma4OefZ8XTD1x62GHIsJSbgcVgjKabqbjaSivMajlDnn5X0v7cBv4bKwvwb7f1RiszVBNM7fK1GjWFvpCjPEE28MLyVVNZVb7C7gkBhKfSKwYcv222aJIh/pV1JBgo9riAI5uvgfMIuaLlq0Ni+WvvapC087t9RvRsVade1vX/yrYNNwhctA00qclT6CezpCR/MPOZXfQiUQcnvhRc4ypziX89psK7PF925w6kgTQ6Od/TSeFxb0zg/JYjemqwRp8LE+zHt3smmwtRoTf0JRsPyvSxsm6pzHFi37HiRDqVQXeiQvSNk77jhwZcGMcPli5l1HG/A1X6zf2Mzbu5e0qtt4sOsefh/MU1p5KK38HIZhDSgwsUChsihbIq1MGhrxciw6Upj1B5bt7D+/NAeJtlToxsL08WmwTKElCrfHh71LCL64aMahtqAvEudqwM1n5WBnGsomyIIZh5jC46d1z7a5tfLZgiLsLaGHZ2qr4QPj//OUjzGklSklxlsQpCImqf81PE6M8lp/ksyquhOHWjWsmfSSBYl7BtC+t93PrlliMokXbTfWnO8tkPM+qaVfeC0Uc2GS50McjbC5BambYirxXPrEL28hji5dlAQ=
  file:
  - build/$PROJECT_BUILD_NAME.tar.gz
  - build/$PROJECT_BUILD_NAME.tar.gz.sha256
  on:
    repo: theckman/cronner
    tags: true
