language: go
go:
- 1.9
addons:
  apt:
    packages:
    - time
sudo: false
notifications:
  email:
    on_success: never
    on_failure: always
env: 'PROJECT_NAME=cronner GOARCH=amd64 GOOS=linux PROJECT_BUILD_NAME="$PROJECT_NAME-$GOOS-$GOARCH-$TRAVIS_TAG"'
install: go get -u github.com/Masterminds/glide
script: go test -v $(glide novendor) -check.vv
before_deploy:
- mkdir build
- mkdir $PROJECT_BUILD_NAME
- go build -o $PROJECT_BUILD_NAME/$PROJECT_NAME
- tar -czf build/$PROJECT_BUILD_NAME.tar.gz $PROJECT_BUILD_NAME/
- shasum -a 256 -- build/$PROJECT_BUILD_NAME.tar.gz | sed -e 's#build/##g' > build/$PROJECT_BUILD_NAME.tar.gz.sha256
deploy:
  provider: releases
  skip_cleanup: true
  file:
  - build/$PROJECT_BUILD_NAME.tar.gz
  - build/$PROJECT_BUILD_NAME.tar.gz.sha256
  on:
    repo: theckman/cronner
    tags: true
  api_key:
    secure: BYFoIL6jJi/OAK/GMiMyHE75ESHSTgvD4kV4WxMvsgeFyJc8X9svRPV845nGo+tbtxtQOqPs3jOyRqbAI/Snuv0b1MUCCpAkNJZn4kc63gQHt79ebSuv58hov3WJrL3S0Pv6lQLqwHAmotRmGl+FvRpS8QxLT4NJsbYFRsCIzv93Aia3+2+NX2xT8p3IE46WI5eZXUPeQ/u3MqKosbi/soYWdY5bybA0vIyio4zcoDZqEb7q88lTlrGA4tkEtzad37PSWjnMguBGtbOsHoZH3vHLYmWdVa2Rsb9Cf54LTvp6d72bKbS9bcIwHw7JBlwDKGQF+sG763prxtHEdvO4hSUOfRH5fOhvFB+JNAt/mPqyTbUhEp6sgfAikJ6BARawhU6HWdKMPAoD5OB3+GFF/hzbWCFrxvSpmxC1QuWNUALwbaPOJEIKfyJ6hMwAIUqKqUEfDfE8hIruW6PSaw2oyfQghQCLPVCetxZh0D0sqFV3M499OSj/UYt51H8o4NvooMTQTO0Dl/tXl8S4UNtXJSRGmMyTlOVOvoNzo6Z8M4e7L7suwwHX2XLe72M764F0izDxpvD2gSz3VsjsZ61xjzupkpVu9Q2AEOY5dvKEimPucq6b8n/QHRd2SFltsFTPP/bsQKd+QBbFVonOhgC91b7paV6W0E91PEBsmCl66JI=
